<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<AssemblyVersion>10.0.0.0</AssemblyVersion>
	<FileVersion>10.0.0</FileVersion>
	<Title>CodedThought.Core.Business</Title>
	<VersionPrefix>10.0.0</VersionPrefix>
	<Version>10.0.0-alpha-1</Version>
	<Authors>Erik Bartlow</Authors>
	<Company>CodedThought</Company>
	<Description>The CodedThought.Core.Business library collection of usefull business focused objects.</Description>
	<PackageProjectUrl>https://github.com/erikbartlow/CodedThought.Core</PackageProjectUrl>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/erikbartlow/CodedThought.Core</RepositoryUrl>
	<IncludeContentInPack>true</IncludeContentInPack>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<IncludeReferencedProjects>true</IncludeReferencedProjects>
	<Copyright>Copyright (c) 2023 Erik Bartlow, All rights reserved</Copyright>
	<PackageReleaseNotes>Upgraded to .NET 8.0.</PackageReleaseNotes>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodedThought.Core\CodedThought.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Update="LICENSE" Pack="true" PackagePath="" />
	<None Update="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
