<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<PackageId>$(AssemblyName)</PackageId>
	<Title>CodedThought Core</Title>
	<ProjectName>CodedThought Core</ProjectName>
	<AssemblyVersion>8.0.1.33</AssemblyVersion>
	<FileVersion>8.0.1.33</FileVersion>
	<Description>The CodedThought.Core library is a custom entity framework used to primarily abstract the database away from consuming components or clients.</Description>
	<Version>8.0.1.33</Version>
	<Authors>Erik Bartlow</Authors>
	<Company>Erik Bartlow</Company>
	<PackageProjectUrl>https://www.nuget.org/packages/CodedThought.Core</PackageProjectUrl>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/erikbartlow/CodedThought.Core</RepositoryUrl>
	<IncludeContentInPack>true</IncludeContentInPack>
	<IncludeReferencedProjects>true</IncludeReferencedProjects>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<Copyright>Copyright (c) 2025 Erik Bartlow, All rights reserved</Copyright>
	<PackageReleaseNotes>Minor fix to the save routines while handling Guid Primary keys. Utilizing the DataTableUsage.AutoGenerateUniqueIdentifier and including Guids in the INSERT statements.</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	<NoWarn>1701;1702;CS0649</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<NoWarn>1701;1702;CS0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
	<Compile Remove="Data\GenericApiDataStore.cs" />
	<Compile Remove="Data\GenericApiDataStoreController.cs" />
	<Compile Remove="Security\LDAPMembershipServices.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="BouncyCastle.NetCore" Version="2.2.1" />
	<PackageReference Include="ChoPGP.Core" Version="1.0.1.2" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
	<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
	<PackageReference Include="Microsoft.Net.Http.Headers" Version="[2.1.14]" />
	<PackageReference Include="SkiaSharp" Version="2.88.8" />
	<PackageReference Include="System.DirectoryServices" Version="8.0.0" />
	<PackageReference Include="System.DirectoryServices.AccountManagement" Version="8.0.1" />
	<PackageReference Include="System.Runtime.Caching" Version="8.0.0" />
  </ItemGroup>

  <Choose>
	<When Condition="'$(Configuration)' == 'Release'">
	  <ItemGroup>
		<PackageReference Include="CodedThought.Core.Configuration" Version="8.0.1" />
	  </ItemGroup>
	</When>
  </Choose>

  <Choose>
	<When Condition="'$(Configuration)' == 'Debug'">
	  <ItemGroup>
		<ProjectReference Include="..\CodedThought.Core.Configuration\CodedThought.Core.Configuration.csproj" />
	  </ItemGroup>
	</When>
  </Choose>
  
  <ItemGroup>
	<None Update="README.md" Pack="true" PackagePath="" />
	<None Update="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
